//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.01.11 at 02:34:16 PM MST 
//


package gov.sandia.gnem.dbutillib.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * DAO
 *
 * <p>Java class for DAO element declaration.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="DAO">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="driver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="tabletablespace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="indextablespace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "type",
        "username",
        "password",
        "driver",
        "instance",
        "filename",
        "tabletablespace",
        "indextablespace"
})
@XmlRootElement(name = "DAO")
public class DAO {

    protected String type;
    protected String username;
    protected String password;
    protected String driver;
    protected String instance;
    protected String filename;
    protected String tabletablespace;
    protected String indextablespace;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the username property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the driver property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDriver() {
        return driver;
    }

    /**
     * Sets the value of the driver property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDriver(String value) {
        this.driver = value;
    }

    /**
     * Gets the value of the instance property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInstance() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInstance(String value) {
        this.instance = value;
    }

    /**
     * Gets the value of the filename property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the tabletablespace property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTabletablespace() {
        return tabletablespace;
    }

    /**
     * Sets the value of the tabletablespace property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTabletablespace(String value) {
        this.tabletablespace = value;
    }

    /**
     * Gets the value of the indextablespace property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIndextablespace() {
        return indextablespace;
    }

    /**
     * Sets the value of the indextablespace property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIndextablespace(String value) {
        this.indextablespace = value;
    }

}
