//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.01.11 at 02:34:16 PM MST 
//


package gov.sandia.gnem.dbutillib.jaxb;

import javax.xml.bind.annotation.*;


/**
 * KBInfo
 *
 * <p>Java class for KBInfo element declaration.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="KBInfo">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice>
 *           &lt;element ref="{}RowGraph"/>
 *           &lt;element ref="{}Schema"/>
 *         &lt;/choice>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "rowGraph",
        "schema"
})
@XmlRootElement(name = "KBInfo")
public class KBInfo {

    @XmlElement(name = "RowGraph")
    protected RowGraph rowGraph;
    @XmlElement(name = "Schema")
    protected Schema schema;

    /**
     * Gets the value of the rowGraph property.
     *
     * @return possible object is
     * {@link RowGraph }
     */
    public RowGraph getRowGraph() {
        return rowGraph;
    }

    /**
     * Sets the value of the rowGraph property.
     *
     * @param value allowed object is
     *              {@link RowGraph }
     */
    public void setRowGraph(RowGraph value) {
        this.rowGraph = value;
    }

    /**
     * Gets the value of the schema property.
     *
     * @return possible object is
     * {@link Schema }
     */
    public Schema getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     *
     * @param value allowed object is
     *              {@link Schema }
     */
    public void setSchema(Schema value) {
        this.schema = value;
    }

}
