//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.01.11 at 02:34:16 PM MST 
//


package gov.sandia.gnem.dbutillib.jaxb;

import gov.sandia.gnem.dbutillib.jaxb.Row.Field;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the gov.sandia.gnem.dbutillib.jaxb package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.sandia.gnem.dbutillib.jaxb
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Relationship }
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link Schema }
     */
    public Schema createSchema() {
        return new Schema();
    }

    /**
     * Create an instance of {@link Row }
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link Column }
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link Field }
     */
    public Field createRowField() {
        return new Field();
    }

    /**
     * Create an instance of {@link RowGraph }
     */
    public RowGraph createRowGraph() {
        return new RowGraph();
    }

    /**
     * Create an instance of {@link TableDefinition }
     */
    public TableDefinition createTableDefinition() {
        return new TableDefinition();
    }

    /**
     * Create an instance of {@link Table }
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link DAO }
     */
    public DAO createDAO() {
        return new DAO();
    }

    /**
     * Create an instance of {@link KBInfo }
     */
    public KBInfo createKBInfo() {
        return new KBInfo();
    }

}
