//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.01.11 at 02:34:16 PM MST 
//


package gov.sandia.gnem.dbutillib.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Relationship
 *
 * <p>Java class for Relationship element declaration.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="Relationship">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="sourceTable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="targetTable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="whereClause" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="constraint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "id",
        "sourceTable",
        "targetTable",
        "whereClause",
        "constraint"
})
@XmlRootElement(name = "Relationship")
public class Relationship {

    protected String id;
    protected String sourceTable;
    protected String targetTable;
    protected String whereClause;
    protected String constraint;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the sourceTable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSourceTable() {
        return sourceTable;
    }

    /**
     * Sets the value of the sourceTable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSourceTable(String value) {
        this.sourceTable = value;
    }

    /**
     * Gets the value of the targetTable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTargetTable() {
        return targetTable;
    }

    /**
     * Sets the value of the targetTable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTargetTable(String value) {
        this.targetTable = value;
    }

    /**
     * Gets the value of the whereClause property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWhereClause() {
        return whereClause;
    }

    /**
     * Sets the value of the whereClause property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWhereClause(String value) {
        this.whereClause = value;
    }

    /**
     * Gets the value of the constraint property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConstraint() {
        return constraint;
    }

    /**
     * Sets the value of the constraint property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConstraint(String value) {
        this.constraint = value;
    }

}
